#!/bin/sh
#
# Connect to Wi-Fi network
#

start() {
	printf "Starting Wi-Fi connection: "
	modprobe brcmfmac
	ip link set wlan0 up
	wpa_supplicant -B -iwlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf -P /var/run/wpa_supplicant.pid
	udhcpc -iwlan0 -p /var/run/udhcpc.pid --syslog --background
	echo "OK"
}

stop() {
	printf "Stopping Wi-Fi connection: "
    start-stop-daemon -K -q -p /var/run/udhcpc.pid
    start-stop-daemon -K -q -p /var/run/wpa_supplicant.pid
    ip link set wlan0 down
    rmmod brcmfmac
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
