#!/bin/sh
#
# Map Arduino serial devices (/dev/ttyACMX) to their /opt/com/ardXX counterpart
#

start() {
	printf "Starting mapping Arduinos: "
	modprobe cdc_acm
    type /sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/tty/ &> /dev/null && ln -s /dev/$(ls /sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.2/1-1.2:1.0/tty/) /opt/cdf/com/ardHG &> /dev/null
    type /sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/tty/ &> /dev/null && ln -s /dev/$(ls /sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/tty/) /opt/cdf/com/ardBG &> /dev/null
    type /sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/tty/ &> /dev/null && ln -s /dev/$(ls /sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0/tty/) /opt/cdf/com/ardHD &> /dev/null
    type /sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/tty/ &> /dev/null && ln -s /dev/$(ls /sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.5/1-1.5:1.0/tty/) /opt/cdf/com/ardBD &> /dev/null
	echo "OK"
}

stop() {
	printf "Stopping mapping Arduinos: "
    rm /opt/cdf/com/ard*
    rmmod cdc_acm
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
