#!/bin/sh
#
# Start main program
#

start() {
	printf "Starting main program: "
    /opt/cdf/run.sh | while read line
    do
        echo "$(cat /proc/uptime | cut -d ' ' -f 1) $line" >> /var/log/programme
    done
	echo "OK"
}

stop() {
	printf "Stopping main program: "
    # TODO We just assume it's okay
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
