#!/bin/sh
#
# Connect to Wi-Fi network
#

start() {
	printf "Starting Wi-Fi connection: "
	modprobe brcmfmac
	ip link set wlan0 up
	wpa_supplicant -B -iwlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf
	udhcpc -iwlan0
	echo "OK"
}

stop() {
	printf "Stopping Wi-Fi connection: "
	killall -q wpa_supplicant
	echo "OK"
}

case "$1" in
  start)
	start &
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
